### ISSUE TITLE
value "1.2" for key "Version" in group "Desktop Entry" is not a known version

### ISSUE THREAD

**Issue by Photon89** [xyproto/gendesk#10]
I get the following error when trying to build unreel (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=unreel#n17):

```
unreel/pkg/unreel/usr/share/applications/unreel.desktop: error: value "1.2" for key "Version" in group "Desktop Entry" is not a known version
unreel/src/unreel.desktop": Failed to validate the created desktop file
```

Looks like the problem occurs since the gendesk update to 1.0.0. Maybe something in the PKGBUILD needs to be changed? 

Thanks for any input!

**Comment by xyproto** [comment]
Thanks for reporting. Changed the version to 1.0, for compatibility.

**Comment by xyproto** [comment]
Related issue: #11

**Comment by Photon89** [comment]
Thanks for the quick fix!
