### ISSUE TITLE
Please target Version=1.0

### ISSUE THREAD

**Issue by probonopd** [xyproto/gendesk#11]
As of this writing, https://standards.freedesktop.org/desktop-entry-spec/latest/ is version __1.2alpha__ but the oldest still-supported distributions, such as CentOS 6 and Ubuntu 14.04, only support __1.0__. Hence this tool should target the version if the spec that the oldest still-supported distributions support out of the box, which currently happens to be 1.0.

Thank you!

**Comment by xyproto** [comment]
Thanks for reporting. Changed the version to 1.0, for compatibility.

**Comment by xyproto** [comment]
Related issue: #10
