### ISSUE TITLE
-git special handling breaks command line flags

### ISSUE THREAD

**Issue by no-preserve-root** [xyproto/gendesk#14]
The suffix special handling in https://github.com/xyproto/gendesk/blob/master/main.go#L338 renames `pkgname` *after* filling the all maps from CLI parameters using the old name (including `-git`) as key. This causes `gendesk` to omit this information from the generated file.

### Reproduction

```
$ gendesk --pkgname test-git --pkgdesc missing
```

### Expected result

```
$ cat test.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Test
Comment=missing
Exec=test
Icon=test
Terminal=false
StartupNotify=false
Categories=Application;
```

### Actual result

```
$ cat test.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Test
Comment=test
Exec=test
Icon=test
Terminal=false
StartupNotify=false
Categories=Application;
```

**Comment by xyproto** [comment]
Thanks for reporting! I'll look into this.

**Comment by xyproto** [comment]
I pushed a fix to `master`. Please confirm that it solves the issue.

**Comment by no-preserve-root** [comment]
Appears to be fixed, thanks!
