### ISSUE TITLE
Resolve variables in variables in PKGBUILD files

### ISSUE THREAD

**Issue by basxto** [xyproto/gendesk#16]
```
_name="emulicious"
pkgname="${_name}-bin"
_exec="${_name}"
```

results in a '${_name}-bin.desktop' with
```ini
Name=${_name}-bin
Exec=${_name}
Icon=${_name}-bin
```

**Comment by xyproto** [comment]
Thanks for reporting! This can be solved by using `--pkgname` and other flags instead, but I'll consider adding the feature you suggest as well.

**Comment by basxto** [comment]
Yes, I could get around it that way, but I tried to avoid calling it like that.
I duplicated the strings for now.
For this specific package I can remove `_name` and `_exec` as soon as 90b764f99ed33f8620584a7df8bb620d50e375d8 gets released.

**Comment by xyproto** [comment]
There's a new release now.

**Comment by xyproto** [comment]
I added simple variable expansion of both $x and ${x} style variables and updated the `main` branch.

Please test if it now works for you.
