### ISSUE TITLE
Allow setting working directory

### ISSUE THREAD

**Issue by JakobDev** [xyproto/gendesk#17]
.desktop files allow settings a custom working directory with Path=. This is a example:
```
[Desktop Entry]
Type=Application
Exec=kdialog --msgbox $PWD
Path=/tmp
```
Would be nice if gendesk had a --path switch for setting the working directory.

**Comment by xyproto** [comment]
Thanks for reporting.

When I've encountered applications that need to be run in a specific directory in the past, the best solution has often been to create a small script that changes the directory and then runs the application. This way, the GUI-application can also be started from the command line in such a way that it is started from the right directory (and then, typically, can find all its files).

I can add a `--path` switch, but are there examples of GUI application that does not benefit more from using a small wrapper script for this purpose?

**Comment by JakobDev** [comment]
I also think that creating a wrapper script is the best solution in the most cases, but there are some cases where you might want to create a extra shortcut with a specific directory. I currently have a non public app.

Anyway, it's the the specification of .desktop files so I think gendesk should support it.

**Comment by xyproto** [comment]
I guess this could potentially be useful. I'll add it.
