### ISSUE TITLE
Add switch to disable Icon

### ISSUE THREAD

**Issue by JakobDev** [xyproto/gendesk#18]
By default gendsek creates a Icon Entry in the .desktop file. But some programs don't have a Icon. So I think it's better to not set the Icon in the .desktop file rather than set it to a non existing Icon. This could be done with a --no-icon flag.

**Comment by xyproto** [comment]
Thanks for reporting.

Do you have an example of a desktop application that does not have an icon?

Would it not be better to add an icon when packaging it?

**Comment by JakobDev** [comment]
A example would be a [small application](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jdreplace) written by me which doesn't have any icon, because it's a really small app and I'm not a artist. I also discovered other small apps which doesn't have icons.

Creating a icon for a app is the job of the person who creates a app. Not the job of the packager.

**Comment by xyproto** [comment]
When packaging GUI applications without an icon, I think the packager should either not package the application, or add a generic icon + report a bug upstream, asking them to add one.

The packager has a responsibility to ensure a minimum of quality and usability for the end user. Why would end users want to install incomplete `.desktop` files without an icon? In my opinion, one of the following would be better:

- To not package it at all.
- To not include a `.desktop` file.
- That the packager includes a generic icon.

Making an attempt at making Linux distros feel more like a whole and less like small components placed next to each other is a responsibility that packagers should take, IMO:

It's also possible to just throw in a short `sed` command in the `PKGBUILD` to remove the `Icon` declaration. I think this makes the `.deskop` shortcut incomplete, though:

```sh
sed '/Icon=/d' guiapp.desktop
```

**Comment by JakobDev** [comment]
I think, if a app has no icon it's better create a shortcut without a icon. I have a few programs with no icon and it does not hurt. The [specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.htmll) also says it's optional, so I'm not the only one with this opinion.

**Comment by xyproto** [comment]
I could add a `--no-icon` flag, and you are right that icons are optional if you look at the spec, but I don't want to support generating what I view as incomplete `desktop` files.

Appending:

```sh
&& sed '/Icon=/d' guiapp.desktop
```

to the `gendesk` command you are using, should accomplish what you want to achieve.

Thank you for creating a feature request, though! Best regards.
