### ISSUE TITLE
Add Exec key field codes

### ISSUE THREAD

**Issue by alecmev** [xyproto/gendesk#19]
For example, for an email client to be able to handle `mailto:` it needs to have `%u` in its desktop file:

```ini
Exec=mail-client %u
```

Right now, the only way to do it is to call `gendesk` with a custom `--exec`:

```bash
gendesk --exec "mail-client %u"
```

Would be nice to be able to instead pass an argument, e.g. `--field-code-u`, that'd tell `gendesk` to append `%u` to `Exec`, to keep it a bit more DRY. For the reference, [here's a table of all the codes](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html).

**Comment by xyproto** [comment]
Thanks for the feature request! I like the idea.

**Comment by xyproto** [comment]
`gendesk` strives to do as much as possible by default, but to be configurable.

Would adding `%u` to the `Exec` line for all application in the "email" category be enough to cover >90% of the cases?

If yes, then application that would need more specific configuration could use a custom `--exec` flag.

**Comment by alecmev** [comment]
Up to you! I feel like there's no the rightest way here. Adding `%u` automatically if there's `Email` in the categories would certainly work for me :slightly_smiling_face: That would happen only when `--exec` isn't passed, right?

**Comment by xyproto** [comment]
Updated the `main` branch. Please test. :slightly_smiling_face:

**Comment by alecmev** [comment]
Thanks! Why not `Contains` instead of `HasSuffix`, without the leading `;`? The category could be `Email;Network;Office;` :slightly_smiling_face:

**Comment by xyproto** [comment]
I agree and updated the code to use `strings.Contains`.

**Comment by alecmev** [comment]
Thank you! :+1:
