### ISSUE TITLE
Emit warning if Gnome category is not well-known

### ISSUE THREAD

**Issue by jose1711** [xyproto/gendesk#21]
https://specifications.freedesktop.org/menu-spec/latest/apa.html contains list of main and additional categories. I think it would be nice if `gendesk` displays a warning if:
  * user fails to mention at least one main category as argument to `--categories`
  * no additional (and well-known) category is listed

This could help avoiding mistakes like running `gendesk` with `--categories Games` instead of `--categories Game;BoardGame` or `science` instead of `Science` etc. There could be an additional argument (off by default) to suppress such warnings.

Optionally a few more category-related checks could be added, such as:
![image](https://user-images.githubusercontent.com/1406222/141990029-d6613428-503c-458a-a565-d53e5aea5130.png)
or hints from Related categories (https://specifications.freedesktop.org/menu-spec/latest/apas02.html) could be shown too.

**Comment by xyproto** [comment]
Thanks for reporting. That's a good idea!
