### ISSUE TITLE
Error on Ubuntu 20.04

### ISSUE THREAD

**Issue by sarmong** [xyproto/gendesk#23]
```
./gendesk-1.0.9-linux/gendesk: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./gendesk-1.0.9-linux/gendesk)
```

What needs to be installed?

**Comment by xyproto** [comment]
Are you using the non-static executable?

Could you please try this one instead?
[gendesk-1.0.9-linux_static.tar.xz](https://github.com/xyproto/gendesk/releases/download/1.0.9/gendesk-1.0.9-linux_static.tar.xz)

**Comment by xyproto** [comment]
Great! I will document the problem and solution.
