### ISSUE TITLE
minor license

### ISSUE THREAD

**Issue by pirate486743186** [xyproto/gendesk#24]
you eat the title "The MIT License (MIT)" ....

**Comment by xyproto** [comment]
* "you eat the title" is nonsensical. What do you mean?
* The string `The MIT License (MIT)` does not exist anywhere in this repository.
* The `LICENSE` file looks correct.
* The `License: MIT` string in `README.md` looks correct.
* GitHub correctly detects that this repository uses the MIT license.

**Comment by xyproto** [comment]
Look at the MIT license example from OSI: https://opensource.org/licenses/MIT

In the license text (between `Begin license text.` and `End license text.`), there is no `The MIT License` title.

Such a title is not part of a standard MIT license.

If `makedeb` requires such a header, then `makedeb` is broken.
