### ISSUE TITLE
Rename default.png

### ISSUE THREAD

**Issue by el-totsira** [xyproto/gendesk#26]
The image downloaded on line 7 of https://github.com/xyproto/gendesk/blob/main/release.sh gets put in `/usr/share/pixmaps/default.png` after packaging for (at least) Arch Linux. Liferea then uses this image instead of its own `/usr/share/liferea/pixmaps/default.svg`.

Apart from the issue of whether Liferea should use gendesk's `default.png` instead of its own `default.svg`, I'm not sure what the use is of including this image in gendesk. If there is no use in including it in releases, I'd be in favour of removing it; I'd rather not have unexpected behaviour in other applications give me screens full of MLP icons :)

(If there's no specific reason to keep the file, I'd be willing to create a PR for this.)

**Comment by xyproto** [comment]
Hi! Thanks for the report!

While including a default.png file is not a bug, in my eyes, I do see the problem.

I'll consider renaming it to gendesk.png instead, if you agree that this would solve the problem.

**Comment by xyproto** [comment]
Liferea should possibly also use a different name than "default".

**Comment by el-totsira** [comment]
I agree that it's not a bug on gendesk's side to include an image of a pony; I've mentioned the origin of the problem in an open issue on Liferea's github page so that perhaps it can be fixed.

Concerning the renaming: I tested it on my computer, and it seems to work around the problem nicely. I would appreciate renaming it to `gendesk.png` very much, as it would allow me to keep gendesk installed without Liferea showing me pages full of ponies :)
