### ISSUE TITLE
Special handling for -git packages

### ISSUE THREAD

**Issue by MCMic** [xyproto/gendesk#3]
It would help if -git suffix was detected and removed from pkgname.

**Comment by xyproto** [comment]
Good point! The feature request is noted. I will see if I can get around to implement this.

**Comment by MCMic** [comment]
Did you have time to look at it?
It seems to be a matter of altering https://github.com/xyproto/gendesk/blob/master/pkgbuildparser.go#L80 to ignore -git suffix if present.

**Comment by xyproto** [comment]
I forgot! Updated the package.

**Comment by MCMic** [comment]
Thanks a lot!
Got another problem now, categories cannot be overridden.
It’s for this package: https://aur.archlinux.org/packages/anticube2-git/
I set _categories to 'Game;' but gendesk still put Application in the desktop file. using --categories cli option does not work either. I’d like to set them so that I can even set a subcategory like LogicGame, and that cannot be autodetected so I need a way to set it manually.

**Comment by xyproto** [comment]
Thanks for reporting! Fixed that one too. Cheers!

**Comment by MCMic** [comment]
Thank you!

**Comment by xyproto** [comment]
Thanks for using gendesk! anticube2 looks interesting.
