### ISSUE TITLE
gendesk and the use of BUILDDIR

### ISSUE THREAD

**Issue by Narrat** [xyproto/gendesk#4]
Hello

Following problem. If using the BULDDIR option from makepkg.conf gendesk fails to find the PKGBUILD, as it searches in the upper directory for it, if not given any PKGBUILD as argument.
Adding PKGBUILD to sources isn't a solution, and I cannot add path to the gendesk call, as I don't know where to which location others download and process the PKGBUILDs.
Is there a env var from the makepkg environment itself that I'm not aware of, which solves this problem?

**Comment by xyproto** [comment]
Hi, no env var yet, but it's a good idea! Will add.

**Comment by xyproto** [comment]
Looked into the issue and could not currently find an exported environment variable that solves this.

Does adding "$SRCDEST/PKGBUILD" as an argument to `gendesk` help?

**Comment by Narrat** [comment]
Propably not in every case, as SRCDEST can be set for a common source directory, so it would fail for someone else

**Comment by xyproto** [comment]
I think this could be solved if `makepkg` exported the `$startdir` environment variable. Submitting a patch to pacman/makepkg is a possibility. If such a patch is not accepted, I guess removing the entire option of taking a `PKGBUILD` file as input to `gendesk` is a possibility.

Not entirely sure what the best solution to this is, but I'm leaning towards a minor change to `makepkg`.

**Comment by xyproto** [comment]
.PKGINFO is generated after, unfortunately.

Replacing this:

    run_function_safe "prepare"

With this:

    (export BUILDDIR; run_function_safe "prepare")

In `/usr/bin/makepkg` will export the BUILDDIR environment variable, but only in the prepare() function when building from a PKGBUILD.

This might, perhaps, be accepted into `/usr/bin/makepkg`, but I would not have too high hopes of the change being accepted. The argument against this would probably be that it is cleaner if `BUILDDIR` is not exposed, and that options should be given directly to `gendesk` instead.

**Comment by xyproto** [comment]
I have thought some more about this, and think that passing arguments to `gendesk`, no matter the method, is the job of the tool/package system calling `gendesk`.

Modifying makepkg to support gendesk is an interesting idea that I would like to look at. Just exposing `BUILDDIR` would make this feature request possible.
