### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by AshotN** [xyproto/gendesk#6]
Is it possible for you to provide binaries? I don't want to ins tall whatever it takes to run Go.

Thanks!

**Comment by xyproto** [comment]
Added a binary release for macOS. Which platform are you on?

**Comment by probonopd** [comment]
Would be great to see for Linux, too. Or maybe even an [AppImage](https://appimage.org/).

**Comment by AshotN** [comment]
I should have mentioned my platform, but I am on Linux.

**Comment by xyproto** [comment]
Added binary releases for:

* FreeBSD/arm6
* FreeBSD/x86_64
* Linux/arm64
* Linux/arm6
* Linux/x86_64
* macOS/x86_64
* Windows/x86_64

https://github.com/xyproto/gendesk/releases/tag/0.7
