### ISSUE TITLE
includes deprecated encoding key

### ISSUE THREAD

**Issue by sevu** [xyproto/gendesk#8]
```
$ desktop-file-validate foo.desktop
foo.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
```
I would propose to include instead the `Version` key, as I have never seen a desktop file without it.
And I was just surprised to find out that there had been two new specifications, 1.2 being the latest.

**Comment by xyproto** [comment]
Thanks for reporting! I will fix this.

**Comment by sevu** [comment]
Wow, what a quick fix.
Turns out 1.2 isn't accepted by desktop-file-validate either, I opened a pull request [upstream](https://gitlab.freedesktop.org/xdg/desktop-file-utils/merge_requests/1), let's see what they say.

**Comment by xyproto** [comment]
Thanks, I found it really confusing that the 1.2 standard wanted the `Version` field to be 1.1 and thought it might be a typo. I am looking forward to the answer from upstream.
