### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by david-redick** [xyproto/gendesk#9]
The LICENSE file is MIT but the bottom of the README.md says GPL2.
Which is it?

**Comment by xyproto** [comment]
Thanks for reporting! It is MIT, will update the README.

GPL2 would also be fine with me, but I am unsure which licence would be most practical for further development and distribution.

**Comment by xyproto** [comment]
Closing this one, but I'm open to changing the license or dual licensing gendesk, if that could be useful!
